<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\WatchBook.Infrastructure\WatchBook.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatchBook.Application\WatchBook.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Models\" />
    <Folder Include="Features\Authentication\Views\" />
    <Folder Include="Features\Catalog\Movie\Models\" />
    <Folder Include="Features\Catalog\Movie\Views\" />
    <Folder Include="Features\Catalog\TvSeries\Controllers\" />
    <Folder Include="Features\Catalog\TvSeries\Models\" />
    <Folder Include="Features\Catalog\TvSeries\Views\" />
    <Folder Include="Features\Social\Controllers\" />
    <Folder Include="Features\Social\Models\" />
    <Folder Include="Features\Social\Views\" />
    <Folder Include="Features\UserContent\Models\" />
    <Folder Include="Features\UserContent\Views\" />
  </ItemGroup>

</Project>
